ALTER SERVER ROLE [sysadmin] ADD MEMBER [LAPTOP-CIKUG36M\MeghanaRao];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

